#!/usr/bin/env bash

# temporary files, repos
tmpdir="/tmp/iddqdidkfa"

# to be moved to .vim or nvim depending on vim type
vimdir=${tmpdir}/vimdir

# plugins
bundledir=${vimdir}/bundle

# color schemes.
# the layout of color schemes directory is:
# colors/
#        something.vim
#        otherthing.vim
colordir=${vimdir}/colors

setUp() {
    set -e 
    rm -rf ${tmpdir}
    mkdir -p ${vimdir}
    mkdir ${bundledir}
    mkdir ${colordir}
}

# set global variable: vimtype
vimtype=
vim_type() {
    vimtype=$( vim --version | perl -ne \
        '/(\w*VIM)\s/ and print $1; exit 0' )
    if [[ "${vimtype}" == "" ]]
    then
        echo "Can not identify the type of vim. Abort."
        exit 1
    fi
}
vim_type

# $1: git repo url
# $2: destination directory
download_one() {
    local url=${1:?"missing git repo url"}
    local dest=${2:?"missing target directory"}
    echo "downloading from ${url}"
    git clone ${url} --depth=1 ${dest} >/dev/null 2>&1 &&
    rm -rf ${dest}/.git
    if [[ $? != 0 ]]
    then
        echo "fail to download to ${dest}"
        exit 1
    fi
}

download() {
    download_one \
        http://github.com/tpope/vim-pathogen \
        ${tmpdir}/pathogen
    mv ${tmpdir}/pathogen/autoload ${vimdir}/

    download_one \
        http://github.com/tpope/vim-sensible.git \
        ${tmpdir}/vim-sensible
    mv ${tmpdir}/vim-sensible ${bundledir}/

    download_one \
        https://github.com/mhartington/oceanic-next \
        ${tmpdir}/_oceanic-next
    mv ${tmpdir}/_oceanic-next/colors/* ${colordir}/

    # polyglot support
    download_one \
        https://github.com/sheerun/vim-polyglot \
        ${tmpdir}/vim-polyglot
    mv ${tmpdir}/vim-polyglot ${bundledir}

    # status line
    download_one \
        https://github.com/vim-airline/vim-airline \
        ${tmpdir}/vim-airline
    mv ${tmpdir}/vim-airline ${bundledir}
}

install_vimdir() {
    local dest=${HOME}/.vim
    [[ ! -d ${dest} ]] && mkdir -p ${dest}
    cp -R ${vimdir}/* ${dest}
}

install_vimdir_neo() {
    local dest=${HOME}/.config/nvim
    [[ ! -d ${dest} ]] && mkdir -p ${dest}
    cp -R ${vimdir}/* ${dest}
}

install_vimrc() {
    cp ./vimrc ${HOME}/.vimrc
}

install_vimrc_neo() {
    local dest=${HOME}/.config/nvim
    [[ -d ${dest} ]] && mkdir -p ${dest}
    cp ./vimrc ${HOME}/.config/nvim/init.vim
}

install() {
    if [[ "${vimtype}" == "NVIM" ]]
    then
        install_vimdir_neo
    else
        install_vimdir
    fi
}

install_rc() {
    if [[ "${vimtype}" == "NVIM" ]]
    then
        install_vimrc_neo
    else
        install_vimrc
    fi
}

setUp
echo "vim is ${vimtype}"
if [[ "$1" == "download" ]]
then
    echo "==============================="
    echo "download only; install manually"
    echo ${vimdir}
    echo "==============================="
    download
    exit 0
fi
if [[ "$1" == "rc"  ]]
then
    echo "=========="
    echo "copy vimrc (neo/vim)"
    echo "=========="
    install_rc
    exit 0
fi
download && install && install_rc
