#!/usr/bin/env bash

tmpdir="/tmp/iddqdidkfa"
vimdir=${tmpdir}/vimdir
bundledir=${vimdir}/bundle
colordir=${vimdir}/colors

setUp() {
    set -e 
    rm -rf ${tmpdir}
    mkdir -p ${vimdir}
    mkdir -p ${bundledir}
}

download() {
    git clone http://github.com/tpope/vim-pathogen --depth=1 ${tmpdir}/pathogen
    rm -rf ${tmpdir}/pathogen/.git
    cp -R ${tmpdir}/pathogen/autoload ${vimdir}/
    
    git clone http://github.com/tpope/vim-sensible.git --depth=1 ${tmpdir}/vim-sensible
    rm -rf ${tmpdir}/vim-sensible/.git
    cp -R ${tmpdir}/vim-sensible ${bundledir}

    # color
    git clone https://github.com/mhartington/oceanic-next --depth=1 ${tmpdir}/_oceanic-next
    cp -R ${tmpdir}/_oceanic-next/colors/* ${colordir}/
}

install_vimdir() {
    local dest_vim=${HOME}/.vim
    rm -rf ${dest_vim}
    mkdir -p ${dest_vim}
    cp -R ${vimdir}/* ${dest_vim}

    cp -R ${colordir} ${dest_vim}/

    local dest_neo=${HOME}/.config/nvim
    if [[ ! -d ${dest_neo} ]]
    then
        return
    fi

    rm -rf ${dest_neo}
    mkdir -p ${dest_neo}
    cp -R ${vimdir}/* ${dest_neo}
    cp -R ${colordir} ${dest_neo}/
}

install_vimrc() {
    cp -f ./vimrc ${HOME}/.vimrc
    
    local neorcdir=${HOME}/.config/nvim
    if [[ -d ${neorcdir} ]]
    then
        cp -f ./vimrc ${HOME}/.config/nvim/init.vim
    fi
}

install() {
    install_vimdir && install_vimrc
}

setUp
if [[ "$1" == "download" ]]
then
    echo "==============================="
    echo "download only; install manually"
    echo ${vimdir}
    echo "==============================="
    download
    exit 0
fi
if [[ "$1" == "rc"  ]]
then
    echo "=========="
    echo "copy vimrc (neo/vim)"
    echo "=========="
    install_vimrc
    exit 0
fi
download && install


