#!/usr/bin/env bash

set -e

thisDir=$( dirname ${0} )

_vimrcPath() {
    echo $( realpath ${thisDir}/vimrc )
}

_vimDirPath() {
    echo $( realpath ${thisDir}/vimdir )
}

# $1: file or dir path
_deleteOrBackup() {
    local aPath=${1}
    local bak=${aPath}.bak
    if [[ -f ${aPath} ]] || [[ -d ${aPath} ]]
    then
        if [[ ! -L ${aPath} ]]
        then
            echo "backing up old file or dir to ${bak}"
            cp -r ${aPath} ${bak}
        else
            echo "deleting current symbolic link"
        fi
        rm -rf ${aPath}
    fi
}

linkRCFile() {
    local source=$( _vimrcPath )
    local dest=${HOME}/.vimrc
    _deleteOrBackup ${dest}
    ln -s ${source} ${dest}
}

linkVimDirectory() {
    local source=$( _vimDirPath )
    local dest=${HOME}/.vim
    _deleteOrBackup ${dest}
    ln -s ${source} ${dest}
}

linkRCFile
linkVimDirectory

